name: Python package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          conda env create -f environment.yml
          eval "$(conda shell.bash hook)"
          conda activate mlops_project
      - name: Start unittest
        run: python testing.py
      - name: Black
        run: |
          eval "$(conda shell.bash hook)"
          conda activate mlops_project
          black --help

